### ISSUE TITLE
Radix<T: 'static>, Stack<T: 'static>?

### ISSUE THREAD

**Issue by jeehoonkang** [spacejam/rsdb#107]
I am porting `rsdb` to crossbeam-epoch (https://github.com/jeehoonkang/rsdb/tree/crossbeam-epoch), and currently, it doesn't compile for lifetime reasons.  In crossbeam-epoch, `fn defer_drop(obj)` requires that `obj` is a `Ptr` to a ` **'static type**:

```rust
unsafe fn defer_drop<T: Send + 'static>(self, ptr: Ptr<'scope, T>);
```

This is because we don't know actually when it will be dropped.  Similarly to `defer_free()`.

However, `rsdb`'s stack and radix doesn't guarantee `T: 'static`.  But it seems all instantiations satisfy this condition.

Do you think it is okay to add the constraint `T: 'static` to both `Radix` and `Stack`?

FYI, here is the compilation error log:

```
   Compiling rsdb v0.11.2 (file:///home/jeehoonkang/Works/rsdb)
error[E0310]: the parameter type `T` may not live long enough
   --> src/ds/radix.rs:126:31
    |
126 |                         scope.defer_drop(old);
    |                               ^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound `T: 'static`...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/ds/radix.rs:126:31
    |
126 |                         scope.defer_drop(old);
    |                               ^^^^^^^^^^

error[E0310]: the parameter type `T` may not live long enough
   --> src/ds/radix.rs:149:28
    |
149 |             unsafe { scope.defer_drop(old) };
    |                            ^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound `T: 'static`...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/ds/radix.rs:149:28
    |
149 |             unsafe { scope.defer_drop(old) };
    |                            ^^^^^^^^^^

error[E0310]: the parameter type `T` may not live long enough
   --> src/ds/stack.rs:183:32
    |
183 |                 unsafe { scope.defer_drop(old) };
    |                                ^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound `T: 'static`...
note: ...so that the type `ds::stack::Node<T>` will meet its required lifetime bounds
   --> src/ds/stack.rs:183:32
    |
183 |                 unsafe { scope.defer_drop(old) };
    |                                ^^^^^^^^^^

error[E0310]: the parameter type `T` may not live long enough
   --> src/ds/stack.rs:188:32
    |
188 |                 unsafe { scope.defer_drop(new) };
    |                                ^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound `T: 'static`...
note: ...so that the type `ds::stack::Node<T>` will meet its required lifetime bounds
   --> src/ds/stack.rs:188:32
    |
188 |                 unsafe { scope.defer_drop(new) };
    |                                ^^^^^^^^^^

error: aborting due to 4 previous errors

error: Could not compile `rsdb`.

To learn more, run the command again with --verbose.
```

**Comment by spacejam** [comment]
For sure! I can add this in about 30 minutes when I get to my office :)

**Comment by spacejam** [comment]
I've uploaded crate version `0.12.0` with these changes!

**Comment by jeehoonkang** [comment]
I successfully compiled the branch: https://github.com/jeehoonkang/rsdb/tree/crossbeam-epoch  Thank you!

<s>Benchmark result will come!</s> May I ask how can I benchmark `rsdb`?

**Comment by spacejam** [comment]
@jeehoonkang I typically run `cargo run --bin=stress2 --release --features=stress -- --duration=10` after tweaking the `src/bin/stress` or `src/bin/stress2` binaries for a particular workload I'm curious about. Note that most of the benchmark will be measuring how fast you can clone materialized pages, as I haven't yet adapted the `PageCache` to return a `Ptr` (and require passing in a scope for calls to `get`). That change should result in a really nice performance improvement.

But if there are any huge regressions you can spot them with `cargo build --bin=stress --features=stress,zstd; hack/flamerun.sh ./target/debug/stress --duration 5; firefox ./flamegraph.svg` (will open `flamegraph.svg` in firefox, change to however you like to view them).

**Comment by jeehoonkang** [comment]
Thank you for detailed documentation on benchmarking!  Unfortunately, there is a significant performance regression.  I ran `cargo run --bin=stress2 --release --features=stress -- --duration=10 ` for both branches:

master:
```
did 99079 ops
did 17 ops
did 141 ops
did 95 ops
did 205 ops
did 162 ops
did 232 ops
did 87 ops
did 309 ops
did 202 ops
did 100529 total ops in 10 seconds. 10052 ops/s
```

crossbeam-epoch:
```
did 22077 ops
did 84 ops
did 74 ops
did 206 ops
did 62720 ops
did 220 ops
did 312 ops
did 275 ops
did 166 ops
did 193 ops
did 86327 total ops in 11 seconds. 7847 ops/s
```

I would like to ask if you could give me any suggestions :)  Thanks!

**Comment by spacejam** [comment]
yikes, I'm used to seeing something like this:
```
did 199249 ops  
did 167710 ops  
did 182589 ops  
did 184253 ops  
did 177618 ops  
did 168987 ops  
did 169206 ops  
did 153867 ops  
did 166599 ops  
did 183048 ops  
did 1753207 total ops in 10 seconds. 175320 ops/s
```

I'd love to see the flamegraph.svg for your system!

This also makes it clear to me that I need to add far better metrics to the system for drilling into issues like this that will pop up on remote systems!

**Comment by jeehoonkang** [comment]
I will file another issue.  Thanks!
