### ISSUE TITLE
implement mvp benchmark calls to db

### ISSUE THREAD

**Issue by spacejam** [spacejam/rsdb#56]
take the arguments, and implement these operations:
1. spin up the specified number of threads
1. execute the desired number of total operations
1. roughly maintain the specified proportion of reads, writes, cas, del, and scan operations among the operations

**Comment by pmuens** [comment]
Quick update on this one that the conversation in #55 should be taken into account here.

Specifically:

- https://github.com/spacejam/rsdb/issues/55#issuecomment-321545616
- https://github.com/spacejam/rsdb/issues/55#issuecomment-322003016
